set(TOOLCHAIN_DIR "/Applications/ArmGNUToolchain/14.2.rel1/arm-none-eabi")
set(TARGET "arm-none-eabi")

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_COMPILER "${TOOLCHAIN_DIR}/bin/${TARGET}-gcc")
# set(CMAKE_CXX_COMPILER "${TOOLCHAIN_DIR}/bin/${TARGET}-g++")
set(CMAKE_ASM_COMPILER "${TOOLCHAIN_DIR}/bin/${TARGET}-gcc")
set(OBJDUMP "${TOOLCHAIN_DIR}/bin/${TARGET}-objdump")
set(OBJCOPY "${TOOLCHAIN_DIR}/bin/${TARGET}-objcopy")
set(SIZE "${TOOLCHAIN_DIR}/bin/${TARGET}-size")

set(CMAKE_EXE_LINKER_FLAGS_INIT "--specs=rdimon.specs")